version: '3.8'
services:
  my-angular-app:
    image: node:14
    volumes:
      - ./my-angular-app:/app
    working_dir: /app
    command: >
      bash -c "npm install -g @angular/cli && ng new my-angular-app --force --skip-git"